### ISSUE TITLE
Add a retry button in case a step run fails to deploy (or for any other reason)

### ISSUE THREAD

**Issue by pratul** [tramlinehq/tramline#337] opened 2023-01-23 11:35 UTC
## Proposal
We need a Retry button in case a step run fails to deploy (or for any other reason). For e.g. 

![image](https://user-images.githubusercontent.com/29076/214029821-c4cdb4f5-c746-4c7a-913b-5f75db83d9bc.png)

## Problems this will solve
At the moment, the only way to resolve a stuck release (due to a build failure or deployment failure) is to land another commit on the release branch. However, even if a user lands an empty commit on the branch, it will increment the version and build number which is probably not the user's intention. 

## Alternatives
The only alternative for now is for the user to land a new commit on the release branch. Git allows empty commits using a special flag: 
```
git commit --allow-empty
```

**Comment by kitallis** [comment] 2023-03-31 10:32
This is a duplicate of #397

**Closed** 2023-09-18 08:01 UTC
Labels: big feature, category / release trains
